### ISSUE TITLE
Question about the project

### ISSUE THREAD

**Issue by mohammadbhuyan** [RTCEngine/rtc-mcu#3]
Hi @notedit,

My understanding is that you are the author of this project. Thanks for helping me to get the GStreamer WebRTC demo running using Python.

Looking at your repos I find that you have essentially have WebRTC work that is of interest to me. Some of it is actually what I am interested to do - a python based WebRC gateway etc.

So I am now keen to get a bit of understanding of what you are doing with WebRTC and if we have alignment in our project objective.

Regards,

Mohammad

**Comment by notedit** [comment]
Yes,  i am going to make a python based WebRTC gateway.  may be even  a webrtc  mcu. 
This is a first goal of this project:

1, File play/record  with webrtc
2, RTSP in/out  with webrtc
3, RTMP in/out with webrtc
this is almost done.  
I will continue to work on this when i am not so busy.

**Comment by notedit** [comment]
@mohammadbhuyan  you can tell me your use case,  maybe  i can help.

**Comment by mohammadbhuyan** [comment]
Hi @notedit, my first objective to stream a camera feed from an embedded / headless system (no browser) to multi-party (browser-based UI) over the internet. It doesn't need to be two-way. Also interested in using the data channel to send control communication from the viewer end to the camera end.

Can we move to this discussion to email so email? Please send me an email to mohammad.bhuyan@gmail.com. I will provide you with a broader context of my project.

**Comment by KaranBE** [comment]
Hi, currently we are using third party WebRTC gateway RTMP video and audio, can i use the project for the same purpose in our production environment.
Thanks

**Comment by notedit** [comment]
@KaranBE  I haven't used this in product.  

you can try my another project  https://github.com/notedit/media-server-go

I will write some WebRTC to RTMP help lib.
